name: restart_app
description: A simple package that helps you to restart the whole android app with a single function call.
version: 1.1.1
homepage: https://github.com/gabrimatic/restart

environment:
  sdk: ">=2.18.4 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: gabrimatic.info.restart
        pluginClass: RestartPlugin
      web:
        pluginClass: RestartWeb
        fileName: restart_web.dart