name: restart_app
description: A Flutter plugin that helps you to restart the whole Flutter app with a single function call by using native APIs.
version: 1.2.1
repository: https://github.com/gabrimatic/restart_app
issue_tracker: https://github.com/gabrimatic/restart_app/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: gabrimatic.info.restart
        pluginClass: RestartPlugin
      ios:
        pluginClass: RestartAppPlugin
      web:
        pluginClass: RestartWeb
        fileName: restart_web.dart